### ISSUE TITLE
'Add Custom Filter' doesn't work on installing v13 web_advanced_search

### ISSUE THREAD

**Issue by MarinkaPapeleuDoria** [OCA/web#1609] opened 2020-05-28 14:24 UTC
On installing the V13 web_advanced_search in Odoo.sh, the 'Add Advanced Filter' is working fine, but the 'Add Custom Filter' from Odoo itself gives the following issue:

Error:

Traceback:
TypeError: Cannot read property 'model' of undefined
    at Class.init (https://marinkapapeleudoria-simlab-staging-26-05-1133685.dev.odoo.com/web/content/4564-c9398dc/web.assets_backend.js:4506:2619)
    at Class.prototype.<computed> [as init] (https://marinkapapeleudoria-simlab-staging-26-05-1133685.dev.odoo.com/web/content/3647-447a04f/web.assets_common.js:3861:488)
    at new Class (https://marinkapapeleudoria-simlab-staging-26-05-1133685.dev.odoo.com/web/content/3647-447a04f/web.assets_common.js:3862:65)
    at Class.select_field (https://marinkapapeleudoria-simlab-staging-26-05-1133685.dev.odoo.com/web/content/4564-c9398dc/web.assets_backend.js:1596:88)
    at Class.changed (https://marinkapapeleudoria-simlab-staging-26-05-1133685.dev.odoo.com/web/content/4564-c9398dc/web.assets_backend.js:1594:1377)
    at https://marinkapapeleudoria-simlab-staging-26-05-1133685.dev.odoo.com/web/content/3647-447a04f/web.assets_common.js:3945:11

**Comment by pedrobaeza** [comment] 2020-05-28 14:25
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in that module. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed as completed by pedrobaeza** 2020-05-28 14:25 UTC
