### ISSUE TITLE
[12.0] web_widget_x2many_2d_matrix: error on timesheet on mobile vire

### ISSUE THREAD

**Issue by FrancoTampieri** [OCA/web#1208] opened 2019-03-06 10:35 UTC
When I try to use the OCA hr_timesheet_sheet on a mobile device I have this error, the matrix fail to render:

> http://localhost:8069/web/content/404-b1154b4/web.assets_backend.js:3179
> Traceback:
> TypeError: Cannot read property 'type' of undefined
>     at Class.<anonymous> (http://localhost:8069/web/content/404-b1154b4/web.assets_backend.js:3179:353)
>     at Function._.each._.forEach (http://localhost:8069/web/content/367-a02552d/web.assets_common.js:12:558)
>     at Class.init_matrix (http://localhost:8069/web/content/404-b1154b4/web.assets_backend.js:3179:248)
>     at Class._render (http://localhost:8069/web/content/404-b1154b4/web.assets_backend.js:3183:6)
>     at Class.prototype.(anonymous function) [as _render] (http://localhost:8069/web/content/367-a02552d/web.assets_common.js:3538:488)
>     at http://localhost:8069/web/content/404-b1154b4/web.assets_backend.js:1041:1521
>     at http://localhost:8069/web/content/367-a02552d/web.assets_common.js:802:681
>     at fire (http://localhost:8069/web/content/367-a02552d/web.assets_common.js:796:299)
>     at Object.add [as done] (http://localhost:8069/web/content/367-a02552d/web.assets_common.js:797:467)
>     at Array.<anonymous> (http://localhost:8069/web/content/367-a02552d/web.assets_common.js:802:649)

Using a normal browser on laptop or server the issue is not performed, if u reduce the size of the screen u can reproduce the error.

Kind Regards

Franco

![screenshot 2019-03-06 11 29 53](https://user-images.githubusercontent.com/4396444/53874685-36347d80-4003-11e9-96a9-78c982a48304.png)

![img_1825](https://user-images.githubusercontent.com/4396444/53875004-ef935300-4003-11e9-8a85-235b65d5c70c.PNG)
![img_1826](https://user-images.githubusercontent.com/4396444/53875005-ef935300-4003-11e9-9c70-f0843561262e.PNG)
![img_1827](https://user-images.githubusercontent.com/4396444/53875006-ef935300-4003-11e9-9982-fe2832dc3b49.PNG)
![img_1828](https://user-images.githubusercontent.com/4396444/53875008-f02be980-4003-11e9-8d23-66c481f22d76.PNG)

**Comment by pedrobaeza** [comment] 2019-03-06 10:37
You should specify which "mobile device". I'm guessing it's iPhone. Please use Firefox for iOS to see if it happens the same.

**Comment by simahawk** [comment] 2019-03-06 10:43
@drdran ciao mate :)
Can you enable debug=assets and trigger again the error?
Then copy paste the txt traceback here.
Thanks

**Comment by FrancoTampieri** [comment] 2019-03-06 10:45
Hi @pedrobaeza 

sure I user Iphone 7 ios 12.1.4.

I have the same issue with firefox 65.0.2 64 bit

![unadjustednonraw_thumb_1e8c](https://user-images.githubusercontent.com/4396444/53875626-36357d00-4005-11e9-927c-ee506beea57c.jpg)

**Comment by FrancoTampieri** [comment] 2019-03-06 10:59
This is the txt when debug=assets is enabled in firefox:

[with_assets_in_firefox.txt](https://github.com/OCA/web/files/2935831/with_assets_in_firefox.txt)

**Comment by simahawk** [comment] 2019-03-06 11:05
weird, seems to fail here 

https://github.com/OCA/web/blob/12.0/web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js#L79

which means that the field for X axis is not there.

If it works on desktop I expect it to work on mobile too, unless for some reason the field is not in `record.data` in mobile which means that the field is not included in the view in mobile :thinking:

**Comment by FrancoTampieri** [comment] 2019-03-06 15:55
Hi mate!

yeah is really strage, the samam problem is in chrome, even I have some problems to open the debug interface with assets, but the message is on the first message of this issue.

Cheers

Franco

**Comment by FrancoTampieri** [comment] 2019-03-12 15:26
As I noticed , but I don0t know if is a bad behaviour of the widget or the timesheet_sheet module, when I use it in wide screen, the inputs after safe, aren't loaded in the respective fiels, look at this images

![Screenshot 2019-03-12 16 24 38](https://user-images.githubusercontent.com/4396444/54212563-6d170180-44e3-11e9-864a-17a82b5b928a.png)

And in the details I have put the timesheet lines, but in the front page I son't see nothing
![Screenshot 2019-03-12 16 24 49](https://user-images.githubusercontent.com/4396444/54212565-6d170180-44e3-11e9-8f89-4d213cfb81cc.png)

Edit: may be the js of the script need a review?

**Comment by DavidLizasoain** [comment] 2019-03-21 15:45
Hello,

Same issue found with Odoo 11 on Ubuntu 16.04, regardless the mobile OS or web browser used.

Anyone any progress since last post 9 days ago? I'd be very gratefull 

Thanks

**Comment by FrancoTampieri** [comment] 2019-03-22 13:52
no I'm not a good javascript developer, I'm a good backend dev, but I can test and help on that

**Comment by FrancoTampieri** [comment] 2019-03-29 10:13
@simahawk Hey Mate!

Can u suggest me a good enviroment to debut Js of odoo? I'm really newbie on that. That may help me to improve this.

Kind regards

Franco

**Comment by simahawk** [comment] 2019-03-29 11:47
@drdran I ping you in pvt ;)

**Comment by FrancoTampieri** [comment] 2019-03-29 11:55
Sure u are welcome!

**Comment by j-zaballa** [comment] 2020-03-27 17:28
Has someone figured out this one? 

I was able to reproduce the issue from Android 9 (Xiami MI A1) both from Chrome and Firefox Focus. I spent some time debugging and saw that the relevant data is already missing when it is retrieved from the model with the `get` function. I'd love to fix it myself, but I'm almost a complete newcomer when it comes to Odoo JS Framework. I'm willing to help though.

**Comment by pedrobaeza** [comment] 2020-06-09 15:35
Is this still happening?

**Comment by FrancoTampieri** [comment] 2020-06-09 19:24
> Is this still happening?

Yes still not working, but unuckily I'm not a javascript expert so I can debug but not fix :(

**Comment by j-zaballa** [comment] 2020-06-10 06:57
Last time I checked, still happening on v11 too. And same here: willing to help, but need some JS guidance.

**Comment by pedrobaeza** [comment] 2020-06-10 07:00
I suppose that is to backport #1404

**Comment by j-zaballa** [comment] 2020-06-11 16:30
> Is this still happening?

Just tried v12 and it works like a charm. I'll try to make a backport to v11. I guess we can close this issue, as it is related to v12.

**Comment by pedrobaeza** [comment] 2020-06-11 16:33
Yes

**Closed as completed by pedrobaeza** 2020-06-11 16:33 UTC

**Comment by j-zaballa** [comment] 2020-06-15 11:01
FYI: I could not make the backport to v11 work. I still get the same error.
