### ISSUE TITLE
Unknown CORS Error

### ISSUE THREAD

**Issue by mrqwertyuiop** [OCA/web#1561] opened 2020-03-25 13:49 UTC
I have installed the module:
[](https://github.com/OCA/web/tree/11.0/web_action_conditionable
)
so, the structure of my odoo application is somehow like this:
odoo:
- server:
- custom:
    - unchanged:
        - web_action_conditionable
    - local:
        - my_module

after installation, I try to use the module, but the result when I try to change my_module tree from this:
`<tree delete="false" create="false">`

to this:

`<tree delete="state=='draft'" create="state!='sent'">`

it would show the warning like this:

![image](https://user-images.githubusercontent.com/39293703/77543050-aa291880-6ed9-11ea-8d81-73b5c9a1c9da.png)

And I also trace the problem use web console, and the result was like this:

> VM5108:1 Uncaught SyntaxError: Unexpected token s in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at Class.init (web.assets_backend.js:1095)
>     at Class.init (web.assets_backend.js:1336)
>     at Class.prototype.<computed> (web.assets_common.js:3816)
>     at Class.init (web.assets_backend.js:2377)
>     at Class.init (web.assets_common.js:3819)
>     at Class.init (web.assets_backend.js:1702)
>     at Class.prototype.<computed> (web.assets_common.js:3816)
>     at Class.init (web.assets_backend.js:1961)
>     at Class.init (web.assets_common.js:3819)

the error points out to the origin package of odoo. 
Does somebody know how to fix this problem?
Please help.

**Comment by Tardo** [comment] 2020-04-19 23:16
12.0 needs this fix: https://github.com/OCA/web/pull/1343

**Comment by pedrobaeza** [comment] 2020-04-19 23:48
Duplicate of #1485

**Closed as completed by pedrobaeza** 2020-04-19 23:48 UTC
