### ISSUE TITLE
[12.0] web_responsive: App drawer search menus not working properly from mobile phone.

### ISSUE THREAD

**Issue by GSLabIt** [OCA/web#1254] opened 2019-04-17 07:49 UTC
Continue from: https://github.com/OCA/web/issues/1251. 

It happens when installing more than 10 apps. Tested in runbot, after last commits search menu doesn't work with virtual keyboard on mobile.

Whatever key is pressed, search input loose focus and doesn't show search results.

https://github.com/OCA/web/pull/1252 fixed when number of app is lower than 10, basically it seems to work properly when drawer has less than 3 rows.

Have a look at video: 
![20190413114412-4b38295101 gif-2-mp4 com](https://user-images.githubusercontent.com/11652845/56077194-7b558780-5dd9-11e9-89da-9dcc6e293c5e.gif)

**Comment by GSLabIt** [comment] 2019-04-17 07:49
@Yajo here it comes

**Comment by yajo** [comment] 2019-04-17 12:25
Fixed in https://github.com/odoo/odoo/pull/32776. The problem is the `barcodes` module. They have to approve that PR, merge it and forward port it to v12. In the mean time you can either:

1. Use Firefox.
1. Do not install `barcodes`.

**Closed as completed by yajo** 2019-04-17 12:25 UTC
