### ISSUE TITLE
web_advanced_search_x2x one2many field error

### ISSUE THREAD

**Issue by szufisher** [OCA/web#146] opened 2015-06-12 05:06 UTC
after install web_advanced_search_x2x  successfully, 
for one2many field, there is error message

 Odoo Client Error

Error: cannot call methods on autocomplete prior to initialization; attempted to call method 'widget'

http://localhost:8080/web/js/web.assets_common/fc0ec0a:216

**Comment by hbrunn** [comment] 2015-06-12 05:34
please activate debug mode and post the error message it provides then

**Comment by rafaelbn** [comment] 2015-08-27 20:46
@szufisher please reproduce issue and post here as indicated. If not please close issue. We cannot reproduce this error.

**Comment by hbrunn** [comment] 2015-09-04 09:34
closing due to obious lack of interest from the side of issue creator

**Closed as completed by hbrunn** 2015-09-04 09:34 UTC
