### ISSUE TITLE
 [10.0] help online Error: QWeb2: Template 'HelpOnline.Button' not found

### ISSUE THREAD

**Issue by m3dbedb** [OCA/web#597] opened 2017-04-07 12:41 UTC
After module  installation, an arror uppears every time I switch to another Odoo application:
`Odoo client error: Error: QWeb2: Template 'HelpOnline.Button' not found`

**Comment by pedrobaeza** [comment] 2018-02-23 00:09
Is this happening also in runbot?

**Comment by m3dbedb** [comment] 2018-02-26 07:48
I can't try it in runbot as long as I've switched to another project after odoo.

**Comment by pedrobaeza** [comment] 2018-02-26 08:28
I don't get you, but this module is working without problems in other environments, so probably the problem is in your end. Closing meanwhile you don't bring more steps to reproduce.

**Closed as completed by pedrobaeza** 2018-02-26 08:28 UTC
