### ISSUE TITLE
[web_widget_many2many_tags_multi_selection] - Model with 2 required fields causes error on "Create..."

### ISSUE THREAD

**Issue by Nimja** [OCA/web#939] opened 2018-05-31 11:06 UTC
[onchange_bug.zip](https://github.com/OCA/web/files/2067543/onchange_bug.zip)
Odoo version: 11
web_widget_many2many_tags_multi_selection version: 11.0.1.0.0

How to reproduce:

* Install Odoo with demo data.
* Download and install attached module: onchange_bug
* *Verify*: `res_partner_category` table has field: `type` (it is filled with default values).
* AFTER installation, modify the file: `./addons/onchange_bug/models/partner_category.py`
* Remove/comment the line: `default='category',` - This line is here so that the module can be installed.
* Edit a contact.
* Write in the tag field: "testing" and click `Create: "testing"` that appears underneath.

Expected result: No error, popup with name + other required field.
* Keep in mind that this is a testing module, the *required* field is currently missing from the form, so saving is impossible. But this is not relevant to the test, as the error appears *before* you can even submit that form.

Current result:
```
Error:
Uncaught TypeError: Cannot read property 'on' of undefined

URL/web/static/src/js/fields/relational_fields.js:290
Traceback:
TypeError: Cannot read property 'on' of undefined
    at slowCreate (URL/web/static/src/js/fields/relational_fields.js:290:20)
    at Object.<anonymous> (URL/web/static/src/js/fields/relational_fields.js:307:25)
    at fire (URL/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as rejectWith] (URL/web/static/lib/jquery/jquery.js:3231:49)
    at Object.<anonymous> (URL/web/static/lib/jquery/jquery.js:3283:104)
    at fire (URL/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as rejectWith] (URL/web/static/lib/jquery/jquery.js:3231:49)
    at Object.deferred.(anonymous function) [as reject] (URL/web/static/lib/jquery/jquery.js:3321:62)
    at Object.<anonymous> (URL/web/static/src/js/services/ajax_service.js:17:32)
    at Object.<anonymous> (URL/web/static/lib/jquery/jquery.js:3276:89)
```

**Comment by pedrobaeza** [comment] 2018-05-31 11:08
Can you attach a custom module for proving this?

**Comment by pedrobaeza** [comment] 2018-05-31 11:08
And please specify version

**Comment by Nimja** [comment] 2018-05-31 11:11
Added versions. I would have to put in some extra effort to create a module to reproduce this (and I don't have time right now). It's pretty easy to do though.

I discovered it by accident because of using it for tags that also have a "Type"
```
    type = fields.Selection(
        string='Type',
        selection=[
            ('category', 'Category'),
            ('geographic', 'Geographic'),
        ],
        required=True
    )
```

**Comment by pedrobaeza** [comment] 2018-05-31 11:15
OK, but if you want this to be reproduced and solved, you have to spend that little time.

**Comment by Nimja** [comment] 2018-05-31 11:31
*nods* I will see if I can make an example model, I just can't close everything I'm working on just to do this.

**Comment by Nimja** [comment] 2018-05-31 11:45
All you do is create a module with one model:

```
# -*- coding: utf-8 -*-
from odoo import fields, models


class Category(models.Model):
    _inherit = "res.partner.category"

    type = fields.Selection(
        string='Type',
        selection=[
            ('category', 'Category'),
            ('geographic', 'Geographic'),
        ],
        default='category',
        required=True
    )
```

File also attached.
[onchange_bug.zip](https://github.com/OCA/web/files/2058047/onchange_bug.zip)

**Comment by pedrobaeza** [comment] 2018-05-31 11:46
@MaxyMoos can you please check?

**Comment by MaxyMoos** [comment] 2018-06-02 08:51
@pedrobaeza Just did ;-)

Unfortunately I cannot reproduce this issue on my side.

I used the basic module written by @Nimja and added the new field to the `res.partner.category` form view (seemed like this was part of the issue but missing from the module).
I can see the new field in the `res.partner.category` form and can create new tags directly from the `res.partner` form view without any issues.

Maybe this is due to an issue within the Odoo code itself.
What Odoo release/commit ID were you testing with @Nimja ?
I've tested with the latest commit of branch 11.0 available as of today (42aff92)

**Comment by pedrobaeza** [comment] 2018-06-02 10:06
Thanks for testing. Waiting for @Nimja's answer, but this seems an issue with one of his custom modules or an outdated Odoo version. If no answer in 7 days, we close it.

**Comment by Nimja** [comment] 2018-06-04 05:29
Will check against latest Odoo without any other modules.

**Comment by Nimja** [comment] 2018-06-04 09:13
I've updated the original post with more detailed test instructions. The only thing that was missing is that the default value CANNOT be set. The issue appears when the frontend attempts to insert and fails.

**Comment by Nimja** [comment] 2018-06-04 09:14
@pedrobaeza - Updated description with more details, I apologize for being not clear enough.

**Comment by MaxyMoos** [comment] 2018-06-04 12:51
@Nimja Thanks for the updated protocol. I've been able to reproduce the issue and the fix seems pretty straightforward so I've opened up a PR.

**Comment by Nimja** [comment] 2018-06-05 06:36
I saw, thank you!
It's just a silly small thing, but it could trip up plenty of people.

**Closed as completed** 2018-06-05 07:36 UTC
