### ISSUE TITLE
[10.0] web_widget_x2many_2d_matrix seems to not work

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/web#625] opened 2017-05-17 08:57 UTC
Hello I am currently migrating a custom module using the widget from 8.0 to 10.0.

Unfortunately it doesn't work. Whatever I do I always get:

![selection_012](https://cloud.githubusercontent.com/assets/7813258/26146180/859fe0c8-3aef-11e7-9ac8-ce0f68ee8f53.jpg)

Do I miss something ?

Thanks for your help.

**Comment by pedrobaeza** [comment] 2017-05-17 09:00
Check the example in https://github.com/OCA/product-variant/blob/10.0/sale_order_variant_mgmt/wizard/sale_manage_variant.py. Note that this is populated in an onchange. Maybe the problem is with Odoo core with default values.

**Comment by Cedric-Pigeon** [comment] 2017-05-17 09:01
I already checked it.
Indeed I don't populate it through an onchange. I simply try to display a One2Many field.

**Comment by pedrobaeza** [comment] 2017-05-17 09:07
As a first test, try to populate your data with an onchange to see if the problem comes from there. Then, we can continue deducing the problem.

**Comment by Cedric-Pigeon** [comment] 2017-05-17 09:24
It don't change anything by onchange.

My field on wizard:
`orderpoint_ids = fields.One2many(string='OrderPoints', comodel_name='mass.stock.orderpoint.wizard.line', inverse_name='wizard_id', ondelete='cascade')`

My corresponding model:
`class MassStockOrderPointWizardLine(models.TransientModel):
    _name = 'mass.stock.orderpoint.wizard.line'
    _description = 'Mass stock inventory minimum level details'

    wizard_id = fields.Many2one(string='Wizard',
                                comodel_name='mass.stock.orderpoint.wizard',
                                required=True,
                                ondelete='cascade')
    product_id = fields.Many2one(string='Product',
                                 comodel_name='product.product',
                                 required=True)
    location_id = fields.Many2one(string='Location',
                                  comodel_name='stock.location',
                                  required=True)
    orderpoint_id = fields.Many2one(string='Minimum Stock Level',
                                    comodel_name='stock.warehouse.orderpoint',
                                    required=False)
    name_x = fields.Char('Name X')
    name_y = fields.Char('Name Y')
    disabled = fields.Boolean(default=False)
    product_min_qty = fields.Float(
        string='Minimum Quantity',
        required=True,
        digits=dp.get_precision('Product Unit of Measure')
    )`

My view:

![selection_013](https://cloud.githubusercontent.com/assets/7813258/26147270/592c570c-3af3-11e7-9fc1-e10e6d43e5de.jpg)

**Comment by Cedric-Pigeon** [comment] 2017-05-17 12:27
The problem comes from this line:
https://github.com/OCA/web/blob/10.0/web_widget_x2many_2d_matrix/static/src/js/web_widget_x2many_2d_matrix.js#L134

I receive objects without any properties.

**Comment by Cedric-Pigeon** [comment] 2017-05-17 12:32
@JonathanNEMRY

**Comment by JonathanNEMRY** [comment] 2017-05-17 12:40
Hi actually there is a strange behavior and we noticed two different things than yours @pedrobaeza (both arrives during the `read_ids` method)

First: If no explicit tree view declared then the read_ids is forced on id only and the returned record is not usable for the following steps of the widget.

Second: with an explicit tree declaration we have one step more: the returned values from the read ids seems good but just after the call into the widget (https://github.com/OCA/web/blob/10.0/web_widget_x2many_2d_matrix/static/src/js/web_widget_x2many_2d_matrix.js#L137) then `rows` is now a empty object event without id...

Anyone has an idea about this strange behavior?  cc @hbrunn ??

Many thanks in advance,

Jonathan

**Comment by pedrobaeza** [comment] 2017-05-18 10:23
@Yajo any clue about this?

**Comment by hbrunn** [comment] 2017-05-22 14:47
do we have the same behavior in 8 too? I didn't review #606, so I've no clue what the current state of the code there is. If this is reproducible in 8, we have a logic error, if not, we need to adapt to behavioral changes in 10.

**Comment by Cedric-Pigeon** [comment] 2017-05-22 14:50
@hbrunn Thanks for reply. The problem is not on V8.0. I face it since I am migrating my module using the widget from 8.0 to 10.0

**Comment by yajo** [comment] 2017-05-29 11:10
I feel the best would be you to migrate the addon and open a pull request (even if it is in WIP status), so we can actually see all the code and test with CI, runbots, etc. With the right diagnose tools, it's quite easier to get a diagnose.

Assuming you'll do this, let me close this for now (please reopen if needed 😉 )

**Comment by Cedric-Pigeon** [comment] 2017-05-30 13:10
@Yajo Could you please re-open the issue ? the addons is already migrated and merged but doesn't work.

**Comment by yajo** [comment] 2017-05-30 14:12
I'm at #ocacodesprint and @jesusVMayor just had the same issue, and it turned out it was an error in his module, not the base one.

**Comment by Cedric-Pigeon** [comment] 2017-05-30 14:18
I am also there. what was the issue ?

**Comment by Cedric-Pigeon** [comment] 2017-06-02 10:24
@pedrobaeza @jesusVMayor Finally, what was done about that during the sprint. I am a little bit confused. The issue is closed by without any solution.

**Comment by pedrobaeza** [comment] 2017-06-02 10:26
No further actions for now because we are still in Barcelona, but let me open the issue again.

**Comment by yajo** [comment] 2017-06-02 10:28
Hey @Cedric-Pigeon, I thought you spoke to @jesusVMayor... 🙊 

Sorry @pedrobaeza, closing again because the bug happened in the sub-module side.

@jesusVMayor had a module that called `read` twice. He just added a line to ignore the call if `ids` parameter was empty, and suddenly all worked OK. @jesusVMayor can you share the code or explain a little bit better please?

**Comment by jesusVMayor** [comment] 2017-06-04 21:42
There is a little confusion here, @Yajo the code that i showed you in the code sprint is the @Cedric-Pigeon  module, and the web_widget_x2many_2d_matrix fails when you create the lines with write. i could not correct it, so the issue should be reopened.

I will continue investigating, but maybe somebody with more experience than me in odoo web client code can find the problem. Everything i could find is when you create the lines with onchange function the `self.dataset.read_ids(self.dataset.ids)` works fine, but when you create it with a write, the function returns an array with all the objects but without data.
I'm sorry if I did not explain myself well and caused this confusion.

**Comment by yajo** [comment] 2017-06-05 10:16
Ah OK np pal, reopening 😉

**Closed as completed** 2017-07-25 16:39 UTC
