### ISSUE TITLE
Issue of Home page and app side bar

### ISSUE THREAD

**Issue by RishabhJadia** [OCA/web#1370] opened 2019-09-10 18:49 UTC
When we login, it goes to sidebar app menu rather it should show home page just like enterprise. Another issue is when I am on home screen and click outside app icon it open existing rendered page as shown in the video.
https://drive.google.com/file/d/1IwVj14H2Ipc12GZJc9vriD5LiTGM4Ynd/view

Thanks,
Rishabh Jadia

**Comment by pedrobaeza** [comment] 2019-09-10 21:35
Which module? Which version? Looking at the video, backend module is not OCA, so closing meanwhile.

**Closed as completed by pedrobaeza** 2019-09-10 21:35 UTC

**Comment by RishabhJadia** [comment] 2019-09-11 03:06
@pedrobaeza  @Tardo Module is web responsive and version is 12.0. home page background is changed by me but its a oca module. Kindly, find the attachment.
![Screenshot_2019-09-11-08-31-59-245_com android chrome](https://user-images.githubusercontent.com/26570284/64665180-41171180-d46f-11e9-8d09-474a85c48109.png)

**Comment by pedrobaeza** [comment] 2019-09-11 07:33
Sorry, but web_responsive doesn't have "sidebar app menu", so it's not the OCA module, but something else. If you touch something, you are the responsible of making it work, or if there's another module, the responsible is that module. Unless the problem is shown with vanilla module (check in runbot), you can't publish an issue here.
