### ISSUE TITLE
[13.0][web_responsive] pivot table col did not show up

### ISSUE THREAD

**Issue by robinhli** [OCA/web#1876] opened 2021-03-24 03:39 UTC
if the col is defined, PC can show no problem, but mobile browser can't show the default col.
you can click the "+" to add col, it's no problem. But it didn't show the default col group even it is defined.

**Comment by pedrobaeza** [comment] 2021-03-24 07:23
Please show screenshots/video of the problem.

**Comment by SplashS** [comment] 2021-03-31 17:04
I confirmed it on last 13.0 and 14.0 runbot.
Steps to reproduce:
1. Install web_responsive and crm modules.
2. Go to CRM Pipeline and switch to pivot view,

Expected behavior:
Pivot grouped by months (rows) and stages (cols).

Actual behavior:
On desktop pivot grouped by months (rows) and stages (cols).
On mobile pivot grouped only by months (rows).

I've reproduced it on Enterprise (demo.odoo.com) also. So it seems that it odoo specific.
May be some heuristic like showing kanban by default on mobile.
Will dig into.

**Comment by SplashS** [comment] 2021-03-31 17:17
I was done deliberately in https://github.com/odoo/odoo/commit/49a97305b1f214b7d27f3de3bd0a91b6c551f8cd
Quote from commit messsage "Performances in mobile mode have been improved by avoiding
unecessary operations due to useless column groupbys in that
mode."
For me it looks strange that we don't use default column grouping on mobile.

**Comment by pedrobaeza** [comment] 2021-04-01 06:47
I don't get yet the problem, but if it was done deliberately, let's close it.

**Closed as completed** 2021-04-01 06:47 UTC
