### ISSUE TITLE
web responsive 14.0 not showing hamburger menu on android

### ISSUE THREAD

**Issue by RodrigoNegrete** [OCA/web#1880] opened 2021-03-24 22:13 UTC
I have installed the latest web responsive (March 24 2021) on 2 linux servers but the hamburger menu doesn´t show on android firefox and chrome.

**Comment by pedrobaeza** [comment] 2021-03-25 07:29
@SplashS can you please check?

**Comment by SplashS** [comment] 2021-03-25 21:21
@RodrigoNegrete Thank you for your feedback.
I have only Android emulator and I've tested last 14.0 runbot on Chrome, Opera. Sorry, but I can't reproduce this problem.
Please give more details.
It's interesting what you did before menu not shown, in which Odoo App it happened, what version of Android and browsers do you have.
If you can't provide all of this information, please share the available information.
I will be trying to reproduce but without information it will be hard.

**Comment by RodrigoNegrete** [comment] 2021-03-26 23:32
@SplashS
Thank you for your response.

CONFIGURATION:
Im using ubuntu 20.04. I tried on an AWS instance, an old mac, and on Virtualbox. All configurations had at least 4GB RAM, 2 processors and 3 workers.
I installed the servers using Yenthee´s script
Using nginx
It´s failing on all apps/modules.
I have the latest android, firefox and chrome.
In windows 10, again on firefox and chrome latest versions, when I shrunk the window to the form of a mobile the hamburger menu wouldn´t appear either. As far as I can remember it did appear on v13

UPDATE:
When I installed the web_responsive module, the main menu wouldn´t show the app icons (just the module names) and the hamburger menu wouldn´t show up. At the time I made sure to refresh all pages, close and opened browsers. 2 days after that (now) I checked again and without any changes from my side, I can confirm that the icons are showing and so is the hamburger menu, meaning everything seems OK on windows and android on both firefox and chrome.
After this I tried to reproduce the error and I installed the module on another instance and got the same initial behavior - no icons and no hamburger menu. I removed cookies, closed browsers and tried again and I still don´t see the icons nor the menu. Im thinking that maybe a full server reboot did the trick so I will make sure not to reboot linux and odoo before I check again in 24 hours. Then I will reboot the system and try again and post my findings.

Please forgive me if the post was an error on my side but I still don´t understand why it miraculously started working by itself after a couple of days.. 
Please let me know if there´s more information that I could provide or some other test I could perform
Thank you very much

**Comment by RodrigoNegrete** [comment] 2021-03-26 23:47
@SplashS
These are the screenshots of the initial behavior
[https://drive.google.com/file/d/18odHTOx_R4CdShFbbi91YgZOn_zEJLdA/view?usp=sharing](url)
[https://drive.google.com/file/d/18tOwKTnZEoJ4Oc9LV3kq8uilKEFujYs6/view?usp=sharing](url)
thanks again

**Comment by RodrigoNegrete** [comment] 2021-03-28 17:02
@SplashS
After waiting for 24 hours I tried to see if the issue resolved by itself but it hadn´t
I restarted only the NGINX server and it didn´t work
After that I stopped and started odoo´s service and everything started working correctly.

To confirm the behavior I created a new server instance and installed web_responsive 14.
After refreshing the webpage I could confirm the initial behavior - No main menu icons and no hamburger menu.
Immediately after that I restarted odoo´s service and the problem was fixed.

CONCLUSION:
I can confirm that the 2 new installations presented the problem prior to an odoo server restart and in all cases it was solved by restarting odoo server.

I hope this information is helpful to you and I thank you and all the Odoo team for your efforts on developing an amazing tool

**Comment by SplashS** [comment] 2021-03-28 17:34
I've tried:
1. to play with "tours version". Since your screenshots have tours enabled but runbot has demo data and tours disabled. This version was not confirmed. Tours work correctly.
2. to reproduce your steps. Run server without web_responsive on disk, after copy module and install it without restarting of server. It works correctly.

According to screenshots it seems that some scripts was not loaded correctly. But root cause is still unknown for me.

@RodrigoNegrete you said that problem reproduces on Desktop browser. So can you check Javascript Console log (press F12 in browser and choose Console tab) and post here any errors or warnings that appear after page loaded.

**Comment by pedrobaeza** [comment] 2021-03-28 19:16
This is a deployment problem, but not a module one, su closing. Check your deployment method.

**Closed as completed by pedrobaeza** 2021-03-28 19:16 UTC
