### ISSUE TITLE
help_online not working in Chrome

### ISSUE THREAD

**Issue by amonang** [OCA/web#193] opened 2015-08-03 04:54 UTC
Tried the help_online module today but it did not work on Chrome (Latest - Version 44.0.2403.125 m). Opened up the same site on Firefox and it worked. Is this a known issue? Are there workarounds?

**Comment by amonang** [comment] 2015-08-03 04:55
Odoo version is 8.

**Comment by pedrobaeza** [comment] 2015-08-03 11:47
I have tried it on runbot and the module is working fine in both browsers, so it should be something on your side. Please try to reproduce the problem in runbot.odoo-community.org.

I close this for now.

**Comment by amonang** [comment] 2015-08-04 04:05
tested the module on runbot although the module installed the button generated is not clickable on Chrome. the tool tip is also not showing ("Create Help page for...")

**Comment by nhomar** [comment] 2015-08-04 05:59
2015-08-03 23:05 GMT-05:00 amonang notifications@github.com:

> tested the module on runbot although the module installed the button
> generated is not clickable on Chrome. the tool tip is also not showing
> ("Create Help page for...")

If you share a little vide, trying it in runbot (not locally, runbot) it
will be more easy to help you @amonang

## 

---

Saludos Cordiales

CEO at Vauxoo https://www.vauxoo.com Odoo's Gold Partner.

[image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
http://about.me/nhomar?promo=email_sig

**Comment by dreispt** [comment] 2015-08-05 15:19
I confirm the issue. It works with Firefox and Edge.
But tried with Chrome (v 44), and the help button does nothing.

**Comment by pedrobaeza** [comment] 2015-08-05 15:29
Uhm, it seems then a regression introduced in a new version of Chrome, because in my version (v38) it works.

**Comment by amonang** [comment] 2015-09-02 13:28
Was trying this again and I hope this info will help.
I did these steps and made the button clickable.
1. On chrome, Right click then inspect element on the button.
2. Drill through until the <a> tag
3. Right click then edit as html
4. Place a letter in between the <a>tags
5. Hover on botton shows the tool tip.
6. Click on button shows the add page dialog box

Although this method adds another icon on the button.

Unfortunately ran out of time today to play around with the js scripts for something more permanent.

**Comment by amonang** [comment] 2015-09-02 13:30
With the tags I mean the < a > tag

**Comment by amonang** [comment] 2015-09-04 13:55
solved this. but I don't know how to send solutions via github.
in the css file help_online.css change display from block to inline-block

``` diff
.openerp .oe_view_manager .oe_view_manager_switch .oe_list_button_help_online:after {
  font-size: 28px;
  content: "?";
  text-align: center;
  margin: 3px auto 4px;
  position: relative;
-display: block;
+display: inline-block;
}
```

**Comment by dreispt** [comment] 2015-09-07 16:54
@lmignon Can you try the fix?

**Comment by lmignon** [comment] 2015-09-08 07:36
@amonang Thank you for the fix! Your change seems to fix the issue. I'm not a CSS guru but with your change, the button works again on chrome.
@dreispt The submitted fix works on chrome.

**Comment by amonang** [comment] 2015-09-08 10:05
@lmignon You're welcome. I'm the one who should be thanking you guys for the incredible work you've been doing. Happy to contribute what I can.

**Comment by pedrobaeza** [comment] 2016-09-28 19:31
This should be solved now.

**Closed as completed by pedrobaeza** 2016-09-28 19:31 UTC
Labels: bug
