### ISSUE TITLE
Header Nav Bar is lapping position

### ISSUE THREAD

**Issue by iampreethamveigas** [OCA/web#789] opened 2017-11-03 11:55 UTC
![screenshot_2017-11-03-17-16-58](https://user-images.githubusercontent.com/24918810/32372684-eab7bb96-c0bb-11e7-8c8b-2632b389f87f.png)

any light to this bug..

**Comment by yajo** [comment] 2017-11-03 13:24
Closing since there's no information on how to reproduce it.

**Closed as completed by yajo** 2017-11-03 13:24 UTC
Labels: needs information

**Comment by iampreethamveigas** [comment] 2017-11-03 17:52
There was a bug in web_responsive module, in Android chrome the header nav bar is overlapping the main body section when you scroll.
installed latest code.
using in odoo 10 .
tested in Samsung j8 chrome.

**Comment by pedrobaeza** [comment] 2017-11-03 17:54
Duplicated with #756

**Comment by iampreethamveigas** [comment] 2017-11-03 17:59
is there any possibilities to fix the bug, i would follow if is there any, i did  went through #756 and dint get any fix so far.

**Comment by pedrobaeza** [comment] 2017-11-03 18:01
No, it isn't. If it remains opened it's because it's not fixed.

**Comment by iampreethamveigas** [comment] 2017-11-03 18:09
ok. hope it ll be get fixed  soon.. or probably do some css workaround.

**Comment by pedrobaeza** [comment] 2017-11-03 18:22
If you are able to fix it, please propose a PR with the fix.
