### ISSUE TITLE
[12.0] Advanced search - Wrong summation when using group by in list view

### ISSUE THREAD

**Issue by JGarcia-Panach** [OCA/web#1517] opened 2020-02-12 13:00 UTC
In runbot:

This is a list view grouped by salesperson using a filter but without using advanced search filter
![image](https://user-images.githubusercontent.com/13234598/74336401-79b07380-4d9e-11ea-97d4-923c0b78520c.png)

All is ok

This is a list view grouped by salesperson using advanced search filter
![image](https://user-images.githubusercontent.com/13234598/74336747-30145880-4d9f-11ea-8c6c-5ca4a7845d8f.png)

**As you see, total does not match.**

There are two sale order lines that meet the search criteria
![image](https://user-images.githubusercontent.com/13234598/74336928-98633a00-4d9f-11ea-8f14-4ea3915ac94f.png)

And as you can see the grouped total is the sale order total multiplied by two

----

If we add another sale order line, we can see the grouped total is total x3
![image](https://user-images.githubusercontent.com/13234598/74337052-dd876c00-4d9f-11ea-9a4e-e77c11ae3bf3.png)

6.552 x 3 = 19656

![image](https://user-images.githubusercontent.com/13234598/74337131-04de3900-4da0-11ea-8711-aa7ed071dd68.png)

**Comment by Tardo** [comment] 2020-02-14 12:30
I can't reproduce the issue.... can you please record a video to see the steps to reproduce? Thanks!

**Comment by JGarcia-Panach** [comment] 2020-02-17 09:29
Tested in this URL:
http://3408529-12-0-2931ed.runbot2.odoo-community.org/web/login

This is the Sale order I use to test: 
![image](https://user-images.githubusercontent.com/13234598/74639513-53a81c00-516e-11ea-87b3-574249b553f8.png)

I change Unit of measure in order to use advanced search (searching lines with Unit of measure = Dozens)

Now the video:
![error advanced](https://user-images.githubusercontent.com/13234598/74640168-6f5ff200-516f-11ea-8529-b03186824145.gif)

As you can see, when you use group by combined with advanced search, the numbers don't match.
When you use group by, it multiplies by the number of hits

In this case (SO021) yo have 2 sale order lines:
![image](https://user-images.githubusercontent.com/13234598/74640484-e7c6b300-516f-11ea-9115-db066377178e.png)

Where total is 18,604.80

If you multily TOTAL by the number of hits (2 order lines found where Unit of measure contains "dozen"): 18,604.80 * 2 = 37,209.60

![image](https://user-images.githubusercontent.com/13234598/74640725-4ee46780-5170-11ea-9d97-a201037bba54.png)

**Comment by JGarcia-Panach** [comment] 2020-03-12 17:17
ping @Tardo

**Comment by Tardo** [comment] 2020-03-13 18:19
@JGarcia-Panach I'm working now in the migration to 13.0 so i hope that the solution is near ;)

**Comment by Tardo** [comment] 2020-03-18 17:56
Bad news... this is a problem in Odoo: https://github.com/odoo/odoo/issues/47950

**Comment by oscars8a** [comment] 2021-02-15 12:19
Hi everyone,

Which one is the state of this problem, with advanced search filter, for Odoo 13.0 and 12.0?
I have this problem in a Odoo 12.0 version.

I have rebuilt the runbot 1551 and I could prove that the problem persists.
I put a git that show the problem in the runbot 1551, and this is the link http://3465288-1551-0732a9.runbot2-3.odoo-community.org/

Thanks a lot.

![Peek 2021-02-15 13-10](https://user-images.githubusercontent.com/33620978/107945796-6ecf8680-6f90-11eb-85f0-6bd9db827ecf.gif)

**Comment by pedrobaeza** [comment] 2021-02-15 12:30
The problem is not on the module, but on Odoo, and it won't be fixed as stated in odoo/odoo#47950, so closing.

**Closed as completed by pedrobaeza** 2021-02-15 12:30 UTC
