### ISSUE TITLE
After installation, open all modules and report errors:

### ISSUE THREAD

**Issue by Aidou-Jacky** [OCA/web#2160] opened 2022-03-07 02:38 UTC
module: web_responsive
version: 14.0

     This error is reported when all modules are opened after installation:Cannot read properties of undefined (reading 'isMobile')

**Comment by pedrobaeza** [comment] 2022-03-07 07:08
It seems you are not installing it correctly or there's an incompatible module, as this is working correctly in runboat. Click on "Runbot: try me" button of the README for checking that is working. Closing meanwhile there's no more evidence of a bug in the module.

**Closed as completed by pedrobaeza** 2022-03-07 07:08 UTC

**Comment by Boca13** [comment] 2022-04-19 14:11
Like Pedro said, the problem is probably related to another module. For example, I've seen the module `ow_web_responsive` cause an error similar to yours.
Also, you could check if you get errors like this in your browser console: `Service web_responsive already defined`.
