### ISSUE TITLE
[13.0] web_domain_field invalid path to static/lib/js

### ISSUE THREAD

**Issue by lck** [OCA/web#1526] opened 2020-02-20 10:33 UTC
Path to pyeval.js is invalid:

13.0/web_domain_field/static/lib/js/pyeval.js

the valid path should be:

13.0/web_domain_field/static/**src**/js/pyeval.js

as declared in web_domain_field/views/web_domain_field.xml

**Comment by legalsylvain** [comment] 2020-02-20 10:59
could you make a PR ? thanks !

**Comment by sudhir-erpharbor** [comment] 2020-02-20 12:35
Thanks for reporting the issue. The issue is fixed in the PR #1527

**Closed as completed** 2020-02-20 13:48 UTC
