### ISSUE TITLE
[14.0] web_search_with_and since last update adds two filters instead of one with "AND"

### ISSUE THREAD

**Issue by pedroguirao** [OCA/web#2291] opened 2022-09-12 09:30 UTC
Hi all!, 

Now if we try to use shift to add the and condition over the second word, odoo adds one OR and one AND, i.e:

We search for "jhon", now we type "walters" and press enter with shift key , odoo searchs for " Jhon OR Walters" AND "Walters".  

## Module
web_search_with_and

**Comment by antoniocanovas** [comment] 2022-10-20 10:18
Please, restore previous version

**Comment by matteoopenf** [comment] 2022-12-14 09:44
Hi, can you proceed to revert last pull request? do you need help? @pedroguirao

**Comment by matteoopenf** [comment] 2022-12-14 09:47
we should remove this commit https://github.com/OCA/web/commit/9bd63dd24ae7c8f8eb9eefd0078b9e19b55cf0cb @pedroguirao  and @antoniocanovas ?

**Comment by pedroguirao** [comment] 2022-12-19 10:08
Hi @matteoopenf sorry for the delay, Yes this last commit changed the behavior. But i cant do a revert AFAIK

**Comment by matteoopenf** [comment] 2022-12-19 10:15
@pedrobaeza  sorry if I quote you.
is it ok, if I will do a manual revert and I revert only the part about this module web_search_with_and, or when I will do a precommit the situation became the same?
Thank you in advance

**Comment by pedrobaeza** [comment] 2022-12-19 10:37
I don't think the problem is with the linter itself, but any incorrect transformation. This shouldn't be reverted, but fixed.

**Comment by matteoopenf** [comment] 2022-12-19 10:40
thank you for reply

> I don't think the problem is with the linter itself, but any incorrect transformation. This shouldn't be reverted, but fixed.

**Comment by matteoopenf** [comment] 2023-02-02 17:13
> Hi @matteoopenf sorry for the delay, Yes this last commit changed the behavior. But i cant do a revert AFAIK

Hi, can you now or you know which is the fix, and I will do the pull request?

thank you

**Comment by altela** [comment] 2023-02-08 15:43
any info regarding this? this affected version 15.0 too, and perhaps also 16.0

**Comment by alessandro-fiorino** [comment] 2023-04-26 07:02
The problem is still here, I reverted to a previous version of the module

**Comment by matteoopenf** [comment] 2023-04-26 07:07
> The problem is still here, I reverted to a previous version of the module

you have done a local revert?

**Comment by alessandro-fiorino** [comment] 2023-04-26 08:55
To avoid messing up with the official branch and future updates, I simply copied an old version of the module in a folder with higher priority in Odoo configuration, so I'll "stick" to that version of this module and keep all the others updated.
If the bug will be fixed I will simply remove the copy from the source tree.

**Comment by matteoopenf** [comment] 2023-04-26 09:01
> To avoid messing up with the official branch and future updates, I simply copied an old version of the module in a folder with higher priority in Odoo configuration, so I'll "stick" to that version of this module and keep all the others updated.
> 
> If the bug will be fixed I will simply remove the copy from the source tree.

I understand

**Comment by qtiplb** [comment] 2023-06-08 19:38
Hi all, I wanted to check if someone is working on this ? We can contribute but just to make sure so that we are not doing a double work.

Thanks!

**Comment by matteoopenf** [comment] 2023-06-08 19:50
> Hi all, I wanted to check if someone is working on this ? We can contribute but just to make sure so that we are not doing a double work.
> 
> Thanks!

If you can contribute  is accepeted

**Comment by matteoopenf** [comment] 2023-06-15 13:15
https://github.com/OCA/web/pull/2531 there is a fix in this pull request if someone can do a review is accepted

**Closed as completed** 2023-06-15 15:00 UTC
Labels: bug
