### ISSUE TITLE
[8.0] web_advanced_search_x2x - Usability in Popup window

### ISSUE THREAD

**Issue by rafaelbn** [OCA/web#194] opened 2015-08-05 12:46 UTC
module: web_advanced_search_x2x
version: 8.0

Steps to reproduce
- Go To Clients
- Unfold advanced search
- Select "Company" (for example)
- Choose option "is in selection"
- In the pop-up window you can check as in the picture that 'X' to close windows hides a little bit

Current behavior

https://cloud.githubusercontent.com/assets/8736623/9080061/83cfe75c-3b50-11e5-811c-90f066c1e066.png

Expected behavior

Must be a little bit more separated

**Comment by pedrobaeza** [comment] 2015-08-05 15:58
I also faced this problem.

@hbrunn, can you please check?

**Comment by rafaelbn** [comment] 2015-08-27 20:47
Please the usability also affect like this, could you give us a tip @hbrunn ?
![09-09-2015 20-03-20](https://cloud.githubusercontent.com/assets/8736623/9770010/e1e47c06-572d-11e5-9096-5a25e5e26183.png)

**Comment by hbrunn** [comment] 2015-08-28 20:19
this must be caused by some interaction between this module and something else. In a nearly vanilla database, it looks like this: 
![ss1](https://cloud.githubusercontent.com/assets/2563186/9556081/43e5f3ae-4dd2-11e5-9e5e-2d91341c7d54.png)
which is not astoundingly beautiful, but that's a known bug. What I see here makes it unusable, but is there chance that this is caused by a tree view (plus contents) so wide you'd have the same problem selecting the same model in a usual search popup window? Please clarify that first: Check if a many2one on the same model behaves differently in it's search popup - the addon uses this without any changes, and if that's broken, it should be fixed there.

**Comment by hbrunn** [comment] 2015-08-28 20:23
to stay in @rafaelbn's example from the beginning: How does the 'Search more' screen look for many2one fields referring to companies? That should have the same problem, I guess

**Comment by hbrunn** [comment] 2015-11-20 13:06
not caused by this module, must be fixed elsewhere

**Closed as completed by hbrunn** 2015-11-20 13:06 UTC
Labels: invalid
