### ISSUE TITLE
[10-11] web_responsive - When creating sales order, cannot see product name until save/reload

### ISSUE THREAD

**Issue by ki1022** [OCA/web#855] opened 2018-02-01 03:26 UTC
When creating a line on a sales order, I cannot see the name or UoM of the product until I save/update the order.  See the attached screenshots of before/after saving a sales order.  This is making is difficult for users to create an order.  Having this problem on odoo CE 10.  Any help with this would be greatly appreciated!

![1](https://user-images.githubusercontent.com/11162300/35659725-bf9f8fda-06ff-11e8-9817-322717da3194.png)
![2](https://user-images.githubusercontent.com/11162300/35659726-bfaeaeca-06ff-11e8-956c-9896d62da5bd.png)

**Comment by pedrobaeza** [comment] 2018-02-01 07:58
Please try to reproduce it on runbot

**Comment by ki1022** [comment] 2018-02-01 22:09
Sorry, I am a bit new to odoo development and have never used runbot before.  I just tried to setup using the instructions provided here:

https://www.odoo.yenthevg.com/installing-and-configuring-your-own-runbot/

..but am getting errors when trying to install the runbot module from this repo: https://github.com/odoo/odoo-extra     Is this the correct module I should be installing?  Error is something like "ParseError: Error while validating constraint   Model not found: runbot.repo"

I did just install the latest version of odoo 10 CE on Ubuntu 16 and I am still having the same problem with the web_responsive addon and sales order.   This is on a fresh test database with no other modules.

**Comment by pedrobaeza** [comment] 2018-02-02 10:38
Oh, no need of setting your own runbot! I'm talking about using OCA's runbot for trying the same to see if you can reproduce the same problem there. This is for avoiding problems with some customization you may have on your own DB. The URL for accessing is:

https://runbot.odoo-community.org/runbot/repo/github-com-oca-web-162

**Comment by ki1022** [comment] 2018-02-02 15:24
Understood.  I was able to login to the backend on this runbot:  https://runbot.odoo-community.org/runbot/162/10.0

..and the problem also happens there.  Whether adding a line on a new sales order or adding to an existing one.

**Comment by pedrobaeza** [comment] 2018-02-02 15:42
Please explain clear steps to reproduce them, without omitting anything (including how you access).

**Comment by ki1022** [comment] 2018-02-02 15:57
1) On a mobile-phone or narrow-width browser, navigate and login to the backend of your odoo
2) Go to "Sales" >" Sales Orders"
3) Click "Create" to begin a new sales order
4) Scroll down to the sales order lines and click Create to add a new product to the order
5) Choose any product and click "Save & Close"

Only the quantity and subtotal will show on the created sale order line, the item name, item code, or UoM is not visible.  These fields only become visible after saving the sales order.  (see images in 1st post).  This also happens when adding a line to an existing sales order, not just new orders.

**Comment by pedrobaeza** [comment] 2018-02-02 16:27
Aha, I think that's the problem! You have to refresh your browser after reducing. It's a limitation on how Odoo works. It happens the same on enterprise interface.

**Comment by ki1022** [comment] 2018-02-02 16:36
I am already aware of that separate issue.  Step 1 just means this is happening on mobile device (narrow) view, I am not resizing the browser window each time.  Please test for yourself on the runbot so you can see what I mean.

*I edited step 1 to be more clear

**Comment by ki1022** [comment] 2018-02-02 21:41
A similar behavior is also happening when adding line items to invoices except the item name says "None" and the subtotal is also missing.  (until saving)

**Comment by ki1022** [comment] 2018-02-07 06:44
Can anyone at least confirm they are also having this issue?  It happens on every version/device I test on.  It's the only thing stopping me from implementing this otherwise great odoo mobile theme.  Thank you!

**Comment by r-moore007** [comment] 2018-02-12 17:48
Also happening here on odoo 10 with web_responsive.  Seems like the javascript is not pulling the product info and injecting back into the sale order page correctly after confirming the order line.  The odoo backend js may have problems identifying the correct elements to update since they differ from the stock layout, I'm not exactly sure.

**Comment by r-moore007** [comment] 2018-02-12 18:21
Here are some screenshots directly from the OCA runbot showing a sales order and an invoice after adding a single line item:

![3316907-10-0-8a3afd runbot2 odoo-community org_web_debug 1 iphone 8 1](https://user-images.githubusercontent.com/36418155/36112358-63750b12-0ff7-11e8-8875-efb7c734d2e3.png)
![3316907-10-0-8a3afd runbot2 odoo-community org_web_debug 1 iphone 8](https://user-images.githubusercontent.com/36418155/36112359-638b6308-0ff7-11e8-8452-72645e5c95a5.png)

This is also preventing removing a line, you can only change qty to 0.  (Normally there is trashcan button to remove line)

**Comment by edesne** [comment] 2018-11-25 07:41
Do you know if there is an alternative to remove a line item?

**Comment by yajo** [comment] 2018-11-26 08:31
Sadly this one is a deliberate design decision from upstream @odoo team, not actually anything that `web_responsive` breaks.

You can check that with their `web_enterprise` happens the same on v10 and v11. On v12 it's fixed by adding a remove button to the popup, as you can see here:

![captura el 2018-11-26 a las 08 28 45](https://user-images.githubusercontent.com/973709/49001709-71e2c000-f155-11e8-9573-62ad28ae31b9.png)

As a workaround, for v11-, you can use your mobile browser's feature to *show computer version* of the page. It's not cool at all, but should do the trick until you migrate to v12.

Closing then, feel free to reopen if needed.

**Closed as completed by yajo** 2018-11-26 08:31 UTC
Labels: enhancement

**Comment by pedrobaeza** [comment] 2018-11-26 08:33
Note that on v12, it has been fixed by Odoo.
