### ISSUE TITLE
Web Responsive Access Denied

### ISSUE THREAD

**Issue by wangsamas** [OCA/web#824] opened 2017-12-13 14:49 UTC
Hi, thanks for this great module.
I install it in odoo 11, and i get this info at production log
Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu
how to fix this?
thx

**Comment by wangsamas** [comment] 2017-12-14 17:07
Hi, I delete group_portal in web.xml and the... 
Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu...
is gone.
Is this okay?

**Comment by lasley** [comment] 2017-12-14 17:10
@wangsamas - please link the line you had to change

**Comment by wangsamas** [comment] 2017-12-14 17:16
Hi lasley,

I don't know how to link the line, I use notepad++
I delete 2 ,global_portal in web.xml file in web_responsive directory

**Comment by lasley** [comment] 2017-12-14 17:18
Are you referring to this? https://github.com/OCA/web/blob/11.0/web_responsive/views/web.xml#L37

**Comment by wangsamas** [comment] 2017-12-14 17:19
Yes, and there is another one below

**Comment by lasley** [comment] 2017-12-14 17:24
Hmmmm I think this has to be an issue with your instance's portal permissions. Deleting those lines is just a temporary fix that will be undone when you update. I think the solution is to instead just add `ir.ui.menu` to the portal read permission in your Odoo instance through the Settings=>Security menu.

I don't have a v11 immediately handy, and our Runbot is broken, so I'm not able to actually confirm that this is indeed a local issue & I will leave this open until someone else (or future me) can confirm.

**Comment by wangsamas** [comment] 2017-12-14 18:24
hi lasley, i just tried add ir.ui.menu read permission to portal user and the result is internal server error.

**Comment by hiltonmw** [comment] 2017-12-15 01:48
I believe this might be a larger issue than you realize.  I too have this issue, as does at least one other customer.  In this case, I cannot even log into my instance's web-GUI at ALL to make any changes.  Can you please assist?  I need to be able to fix this so I can re-access my system.  It's been down for two full days now, without me changing anything.... more details can be found here...
https://community.bitnami.com/t/odoo-11-vm-acls-suddenly-broken/54064/11

**Comment by hiltonmw** [comment] 2017-12-15 01:49
I need to know how to change permissions through postgres on the server (SSH'd in) or something else, because my server is 100% down now because of this problem.

**Comment by lasley** [comment] 2017-12-15 02:04
If your server is down, I'd try removing the suspect module from the file system and trying again. You'll get console errors, but your site will work. Or edit the lines mentioned above and update the module.

I just tested on my own instance, and there is something wrong with the permissions in both of your instances. Without information regarding what other specific module caused this confliction though, I cannot form a guess as to what.

`web_responsive` does not interact with permissions in any way, so it's not possible for it to cause your permissions errors. Furthermore, [this same permission is on the core Odoo web client's navbar](https://github.com/odoo/odoo/blob/11.0/addons/web/views/webclient_templates.xml#L629), so uninstalling `web_responsive` will not fix the issue.

I'm closing this.

**Closed as completed by lasley** 2017-12-15 02:04 UTC
Labels: question

**Comment by wangsamas** [comment] 2017-12-15 11:19
Hi lasley, you are right that deleting group_portal is just a temporary fix.
btw, I agree that web_responsive suppose not interact with permissions in any way.
but I really keep my eye on production.log

Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu
Doesn't show when I uninstall web_responsive.
It show right away I install web_responsive.

I don't know what should I do.

**Comment by pedrobaeza** [comment] 2017-12-15 11:20
I confirm this is not something of web_responsive. I have it in production in 11.0 without problems.

**Comment by wangsamas** [comment] 2017-12-15 12:21
hi pedrobaeza,
have you look at your production.log ?
We don't see any anything in ussage. seems no problem, but there are something going on in production.log 

I've tried again and again now... install, uninstall, install, uninstall, install, uninstall, install, uninstall...
if I install web_responsive, I get this message in my production.log
Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu
if I install any other apps(e.g CRM) after I install web_responsive, I get that message again
if I install CRM before / without web_responsive, I don't get that message.

Again... all functioning well with web_responsive installation. there is nothing wrong with the ussage.
But there are "Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu" message in the production.log

**Comment by pedrobaeza** [comment] 2017-12-15 12:30
No, no log with errors by my part...

**Comment by hiltonmw** [comment] 2017-12-15 18:50
Anyone know how I might be able to update the ACLs through PGAdmin directly in Postgres?  I'm really stuck here!

**Comment by lasley** [comment] 2017-12-15 18:53
@hiltonmw - your issue sounds completely unrelated here, particularly given that the report here is a log-only issue. I recommend you hire an Odoo integrator if you are about to try to edit ACLs in the database.

@wangsamas - I tested on a local, and even installed all modules that Odoo SA provides as part of core - in hopes that I could trigger the error in the logs. Can you provide a full traceback, please?

**Comment by lasley** [comment] 2017-12-15 19:00
@wangsamas - also are you maybe on Linux? If so, you could probably find the addon that did mess things up like this:

```
grep --include=\*.{xml,csv} -rnw '/path/to/addons/not/in/core/' -e "base.group_portal"
```

**Comment by wangsamas** [comment] 2017-12-15 19:16
Hi lasley,

I don't know how to full traceback. but this is what I get in my log when I install an app without web_responsive (mass mailing app)

2017-12-15 19:14:19,257 4744 INFO wangsamas odoo.addons.base.ir.ir_http: Generating routing map
2017-12-15 19:14:22,680 4744 INFO wangsamas odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [444, 443]
2017-12-15 19:14:23,225 4744 INFO wangsamas odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [243]
2017-12-15 19:14:24,243 4744 INFO wangsamas odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [445]
2017-12-15 19:14:24,391 4744 INFO wangsamas odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [247]

And this is what I get with web_responsive. 
the same mass mailing app, I uninstall, install web_responsive, then install mass mailing app again

2017-12-15 19:13:00,547 4744 INFO back odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [795]
2017-12-15 19:13:01,623 4744 INFO back odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [816]
2017-12-15 19:13:01,782 4744 INFO back odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [798]
2017-12-15 19:13:02,288 4744 INFO back odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu
2017-12-15 19:13:02,301 4744 INFO back odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu
2017-12-15 19:13:02,330 4744 INFO back odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu
2017-12-15 19:13:02,354 4744 INFO back odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu

**Comment by lasley** [comment] 2017-12-15 19:29
@wangsamas Well that's weird. Ok so to replicate this, we have to install a module? I figured it would be when you refresh a page.

I just tried uninstalling mass mailing, then reinstalling (under the demo user with default permissions + settings), and I'm not seeing it still. I'm even seeing successful queries to `ir.ui.menu` for the loading of the icons:

```
2017-12-15 19:24:27,767 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:27] "GET /web/content/1063-151c918/web.assets_backend.js HTTP/1.1" 200 -
2017-12-15 19:24:28,720 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:28] "GET /web/image/ir.ui.menu/77/web_icon_data HTTP/1.1" 304 -
2017-12-15 19:24:28,742 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:28] "GET /web/image/ir.ui.menu/242/web_icon_data HTTP/1.1" 304 -
2017-12-15 19:24:28,773 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:28] "GET /web/image/ir.ui.menu/315/web_icon_data HTTP/1.1" 304 -
2017-12-15 19:24:28,809 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:28] "GET /web/image/ir.ui.menu/204/web_icon_data HTTP/1.1" 304 -
2017-12-15 19:24:28,830 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:28] "GET /web/image/ir.ui.menu/319/web_icon_data HTTP/1.1" 304 -
2017-12-15 19:24:28,850 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:28] "GET /web/image/ir.ui.menu/157/web_icon_data HTTP/1.1" 304 -
2017-12-15 19:24:28,873 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:28] "GET /web/image/ir.ui.menu/146/web_icon_data HTTP/1.1" 304 -
2017-12-15 19:24:28,892 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:28] "GET /web/image/ir.ui.menu/502/web_icon_data HTTP/1.1" 304 -
2017-12-15 19:24:28,918 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:28] "GET /web/image/ir.ui.menu/521/web_icon_data HTTP/1.1" 304 -
2017-12-15 19:24:28,936 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:28] "GET /web/image/ir.ui.menu/405/web_icon_data HTTP/1.1" 304 -
2017-12-15 19:24:28,957 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:28] "GET /web/image/ir.ui.menu/467/web_icon_data HTTP/1.1" 304 -
2017-12-15 19:24:28,982 1352 INFO test werkzeug: 10.0.2.2 - - [15/Dec/2017 19:24:28] "GET /web/image/ir.ui.menu/554/web_icon_data HTTP/1.1" 304 -
```

I logged out and then tried hitting one of the icon URIs, and was then able to replicate. Basically this just means that the permissions were correct on the logged in user, and these files aren't avail for public access.

```
2017-12-15 19:26:15,655 1352 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu
2017-12-15 19:26:15,657 1352 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu
2017-12-15 19:26:15,660 1352 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu
2017-12-15 19:26:15,664 1352 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: ir.ui.menu
```

There's another module in play here that edited ACLs for `ir.ui.menu`. I would try the grep [above](https://github.com/OCA/web/issues/824#issuecomment-352085229) and maybe try switching `base.group_portal` for `ir.ui.menu` if you don't get any good results. 

I can absolutely 100% without a doubt guarantee you though that the culprit is not `web_responsive`. Once you do find it, if it's an OCA module, please create an issue in the proper repo so we can get it handled.

**Comment by wangsamas** [comment] 2017-12-15 19:34
Yes I use linux. 

I couldn't find grep --include=\*.{xml,csv} -rnw '/path/to/addons/not/in/core/' -e "base.group_portal"

this is what i found with grep

C:\Users\wangsamax\Documents\Odoo11\OKE\addons\hw_blackbox_be\controllers\main.py (1 hit)
	Line 176:             return subprocess.check_output("ifconfig eth0 | grep -o 'HWaddr.*' | sed 's/HWaddr \\(.*\\)/\\1/' | sed 's/://g'", shell=True).rstrip()[-7:]

  C:\Users\wangsamax\Documents\Odoo11\OKE\addons\hw_escpos\controllers\main.py (4 hits)
	Line 198:         hosting_ap = os.system('pgrep hostapd') == 0
	Line 199:         ssid = subprocess.check_output('iwconfig 2>&1 | grep \'ESSID:"\' | sed \'s/.*"\\(.*\\)"/\\1/\'', shell=True).rstrip()
	Line 200:         mac = subprocess.check_output('ifconfig | grep -B 1 \'inet addr\' | grep -o \'HWaddr .*\' | sed \'s/HWaddr //\'', shell=True).rstrip()
	Line 200:         mac = subprocess.check_output('ifconfig | grep -B 1 \'inet addr\' | grep -o \'HWaddr .*\' | sed \'s/HWaddr //\'', shell=True).rstrip()

  C:\Users\wangsamax\Documents\Odoo11\OKE\addons\mail\models\mail_tracking_value.py (2 hits)
	Line 100:         # grep : # old_value_integer | old_value_datetime | old_value_char
	Line 105:         # grep : # new_value_integer | new_value_datetime | new_value_char

**Comment by wangsamas** [comment] 2017-12-16 08:33
Hi lasley, This might sound silly, but I want to try to give somekind of access permission to web_responsive for everyone.
I read from odoo documentation, I suppose I make a security directory with 2 files in it? a csv & a xml?

id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
..., ..., ..., ..., ..., ..., ..., 

and

`<odoo>`
SOMETHING HERE
`</odoo>`

Please help me what should I put in there, for I have no idea at all.

**Comment by wangsamas** [comment] 2017-12-16 08:55
hi again,

suddenly I get this other error right after the access denied. Is this has something to do with the access denied issue or is it something else?

2017-12-16 08:28:45,043 15491 ERROR wangsamas odoo.addons.website.models.ir_http: 500 Internal Server Error:
Traceback (most recent call last):
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fb02b7a4128>
.
.
.
.
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/api.py", line 961, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/api.py", line 993, in getter
    raise exception
odoo.exceptions.MissingError:

**Comment by lasley** [comment] 2017-12-22 17:40
@wangsamas Absolutely every user derives from either `base.group_user,base.group_portal`, so permissions already exist for all of them for the most part. 

You would need to ask the Odoo SA team why this permission exists, because it was simply transferred into this addon in order to mirror the existing interface API as much as possible. 

This boils into a common issue with Odoo - permissions. I've personally gone down this rabbit hole and seriously screwed some Odoo instances up. 

The complexity and specificity of this issue though means that you are either doomed to many hours of personal suffering, or you'll need to fork up money for someone with a higher skill level. 

I'm not trying to be a dick here, but fixing something like this needs actual poking into the system. If you are able to identify an addon that did actually cause this, then by all means please submit an issue for it. The thing though is that this issue can just as easily be caused by a user, and diagnosing that takes big effort.

**Comment by lasley** [comment] 2017-12-22 17:45
A hammer approach that may work is taking production down for a long time & simply starting Odoo with `--update=all`. It could also make things significantly worse.

**Comment by wangsamas** [comment] 2017-12-23 03:58
Hi Lasley, you are awesome! absolutely not a dick and your information is very useful for me.
I did asked in odoo forum, but has no respon yet.

For now the conclusions are this is not my mistake and this is not caused by web_responsive or bitnami package or debian?

There are some things that i suspect.
1. I missed something to installed that needed for odoo to run well.
2. I have to give permission for something to do something in odoo.
3. This is an odoo bug that completely beyond my reach

I really still wonder is this just me or someone else has the same problem. Because i didn't found someone else report the same problem.

**Comment by lasley** [comment] 2017-12-23 18:29
@wangsamas - I find it unlikely that an addon caused this problem, although it's possible. Definitely not number 1, or 2. Possibly 3, but I doubt it.

Typically permissions issues are human caused, so either by something you did or (more likely) something a user did. It's possible for a module, but dropping the `ir.ui.menu` permissions from either the portal or user groups is not something that would pass an OCA QA (I hope), so I would be willing to lay money on the fact it's not an OCA addon that caused this. 

Try backing everything up, then the `--update=all`. That'll restore default permissions from core, which is where this all is. That's usually my failsafe solution for any problem before I start manually doing anything. It's possible to wreck the instance more though, hence backup. 

Good luck!

**Comment by hiltonmw** [comment] 2017-12-23 20:30
lasley, where would i run --update-all from?  I'm using the bitnami stacks version and cannot seem to find where openerp-server resides...

**Comment by lasley** [comment] 2017-12-23 20:53
Dunno anything about Bitnami, but you need to append that to the standard Odoo start command. `ps aux|grep odoo` might help

**Comment by wangsamas** [comment] 2017-12-24 14:37
@hiltonmw
I think it's similar to restart command from bitnami stack tutorial, but change the restart to update all.

@lasley
Sorry to bother you again. You are the best answer i get. I use google cloud and haven't use it for real transactions. So it's okay for me to change os or restart from the beginning.
There are some questions that i still don't understand.
1. What is the best os for odoo? Debian, ubuntu, windows, or else???
2. I believe you are not using bitnami stack package for installing odoo, but you are also can get the access denied. So it seems like an odoo 11 bug?
3. You are mention about base.group_user and base.group_portal. I didn't see group_user in group setting. I see group_public, group_portal and group employee. Most of other group inherited from employee, admin is not inherit from employee or other group. Can this be the problem? Odoo team forget Group_user ?

**Comment by wangsamas** [comment] 2018-01-08 02:25
@lasley 

I try ps aux|grep odoo, I get this and have no idea what it's mean.
please help

daemon    4505  0.0  2.0 596948 35624 ?        Sl   Jan07   0:00 /opt/odoo11/apache2/bin/httpd.bin -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
postgres  5670  0.0  3.9 204140 68476 ?        Ss    2017   0:05 
postgres: bn_odoo kim 127.0.0.1(33808) idle
daemon    5685  0.0  1.3 373932 23688 ?        Sl   Jan07   0:00 /opt/odoo11/apache2/bin/httpd.bin -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
postgres  5774  0.0  3.8 204052 67180 ?        Ss    2017   0:14 postgres: bn_odoo kim 127.0.0.1(33952) idle
postgres  5923  0.0  3.8 201672 66804 ?        Ss    2017   0:05 postgres: bn_odoo kim 127.0.0.1(34116) idle
daemon    7017  0.0  1.5 374056 27148 ?        Sl   01:47   0:00 /opt/odoo11/apache2/bin/httpd.bin -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
postgres  7175  0.0  2.0 190616 36536 ?        Ss   01:58   0:00 postgres: bn_odoo wangsamas 127.0.0.1(56534) idle
daemon    7176  0.0  1.3 372824 23116 ?        Sl   01:58   0:00 /opt/odoo11/apache2/bin/httpd.bin -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
daemon    7177  0.0  1.4 447072 24712 ?        Sl   01:58   0:00 /opt/odoo11/apache2/bin/httpd.bin -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
postgres  7192  0.0  2.0 190596 36336 ?        Ss   01:59   0:00 postgres: bn_odoo wangsamas 127.0.0.1(56558) idle
postgres  7196  0.0  1.8 189860 31532 ?        Ss   01:59   0:00 postgres: bn_odoo wangsamas 127.0.0.1(56562) idle
postgres  7294  0.0  4.2 203132 74600 ?        Ss    2017   0:18 postgres: bn_odoo kim 127.0.0.1(35094) idle
postgres  7295  0.0  4.1 202720 71916 ?        Ss    2017   0:07 postgres: bn_odoo kim 127.0.0.1(35096) idle
wangsam+  7482  0.0  0.0  12784   944 pts/0    S+   02:22   0:00 grep odoo
postgres  8695  0.0  3.1 194816 55040 ?        Ss    2017   0:00 postgres: bn_odoo kim 127.0.0.1(36702) idle
daemon   15828  0.0  3.2 597172 55904 ?        Sl   Jan06   0:03 /opt/odoo11/apache2/bin/httpd.bin -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
daemon   16869  0.0  2.2 596968 39496 ?        Sl   Jan06   0:04 /opt/odoo11/apache2/bin/httpd.bin -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
daemon   17255  0.0  2.2 523188 39168 ?        Sl   Jan06   0:03 /opt/odoo11/apache2/bin/httpd.bin -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
postgres 17782  0.0  2.4 192756 42420 ?        Ss    2017   0:11 postgres: bn_odoo wangsamas 127.0.0.1(43900) idle
postgres 21954  0.0  1.9 190820 33760 ?        Ss    2017   0:00 postgres: bn_odoo cishesa 127.0.0.1(46192) idle
postgres 21955  0.0  2.0 192928 35280 ?        Ss    2017   0:00 postgres: bn_odoo cishesa 127.0.0.1(46194) idle
postgres 24045  0.0  1.6 190428 29484 ?        Ss    2017   0:00 postgres: bn_odoo cishesa 127.0.0.1(47510) idle
postgres 24046  0.0  1.8 190788 33068 ?        Ss    2017   0:00 postgres: bn_odoo cishesa 127.0.0.1(47512) idle
postgres 24047  0.0  1.9 189916 33260 ?        Ss    2017   0:00 postgres: bn_odoo cishesa 127.0.0.1(47514) idle
postgres 24049  0.0  1.7 190404 30676 ?        Ss    2017   0:00 postgres: bn_odoo cishesa 127.0.0.1(47516) idle
postgres 24050  0.0  1.7 190696 30804 ?        Ss    2017   0:00 postgres: bn_odoo cishesa 127.0.0.1(47518) idle
daemon   27184  0.0  3.0 597268 53860 ?        Sl   Jan05   0:06 /opt/odoo11/apache2/bin/httpd.bin -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
daemon   29936  0.0  2.0 595704 35452 ?        Sl   Jan07   0:01 /opt/odoo11/apache2/bin/httpd.bin -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
postgres 31725  0.0  1.0 186488 17448 ?        S     2017   0:43 /opt/odoo11/postgresql/bin/postgres.bin -D /opt/odoo11/postgresql/data
daemon   31747  0.0 12.3 449300 215804 ?       Sl    2017  22:49 /opt/odoo11/python/bin/python3 /opt/odoo11/apps/odoo/bin/odoo-bin gevent -c /opt/odoo11/apps/odoo/conf/odo
o-server.conf --max-cron-thread 0 --db-filter=^%d$
daemon   31773  0.0  5.2 388452 90960 ?        Sl    2017   5:05 /opt/odoo11/python/bin/python3 /opt/odoo11/apps/odoo/bin/odoo-bin -c /opt/odoo11/apps/odoo/conf/odoo-serve
r.conf --max-cron-thread 1 --db-filter=^%d$
postgres 31781  0.0  2.3 192432 40420 ?        Ss    2017   0:13 postgres: bn_odoo wangsamas 127.0.0.1(57224) idle
postgres 31783  0.0  2.3 192376 40312 ?        Ss    2017   0:12 postgres: bn_odoo wangsamas 127.0.0.1(57226) idle
root     31794  0.0  1.6 216816 28632 ?        Ss    2017   0:44 /opt/odoo11/apache2/bin/httpd.bin -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
daemon   31797  0.0  0.8 494564 15268 ?        Sl    2017   0:51 (wsgi:wsgi-odoo)                  -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
daemon   31798  0.0  0.8 429028 15268 ?        Sl    2017   0:50 (wsgi:wsgi-odoo)                  -f /opt/odoo11/apache2/conf/httpd.conf -DDISABLE_BANNER
postgres 31848  0.0  0.5 187280  9588 ?        Ss    2017   0:00 postgres: bn_odoo postgres 127.0.0.1(57238) idle

**Comment by wangsamas** [comment] 2018-01-19 17:20
@lasley

I've bring this issue to bitnami community and they are also able to reproduce this ACL warning
https://community.bitnami.com/t/odoo-addons-website-models-ir-http-500-internal-server-error/54176/20

They try to give solution by install phonenumbers, but it doesn't work
It seems that someway somehow web_responsive block odoo server to recognize who is coming.

This is my recent warning

2018-01-19 16:59:44,401 20149 INFO wangsamas odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 10, model: ir.model
2018-01-19 16:59:44,407 20149 WARNING wangsamas odoo.addons.website.models.ir_http: 403 Forbidden:

You can see that 403 warning that I get has the same time with ACL access denied. And at the end of the 403 warning log show.

odoo.exceptions.AccessError: ('Sorry, you are not allowed to access this document. Only users with the following access levels are allowed to do that:\n- Employees/Employee\n\t- Administration/Access Rights\n\t- Employees/Employee\n\n(Document model: ir.model)', None)


So... I use Administration/Access Rights when I access, but it said that I cannot access, only Administration/Access Rights allowed to access, and I still can access anyway.???

Please help

**Comment by lasley** [comment] 2018-01-22 16:28
@wangsamas - I'm sorry to be so blunt here, but this is not my problem. You are welcome to hire someone to solve this for you.

**Comment by wangsamas** [comment] 2018-01-23 05:00
@lasley 
thx & sorry for bothering you

**Comment by wangsamas** [comment] 2018-02-07 17:46
@lasley 
Sorry to bother you again.
I found that this code in web_responsive/views/web.xml cause the Access Denied

                <img t-attf-src="/web/image/ir.ui.menu/{{ menu['id'] }}/web_icon_data"
                     class="app-drawer-icon-app img-rounded"
                     t-att-alt="menu['name']"
                     t-att-title="menu['name']"
                     />

I delete the code and the Access Denied are gone.
Is there any other way to fix this ?

**Comment by lasley** [comment] 2018-02-07 17:49
@wangsamas - Those are the application icons. Do you know which of them is causing the access denied? The network tab in your browser's developer console might tell you - just look for the one with the 4xx response.

**Comment by wangsamas** [comment] 2018-02-07 18:21
@lasley 
The Access denied written 
odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: **ir.ui.menu**

so I suspect the **ir.ui.menu** in t-attf-src="/web/image/**ir.ui.menu**/{{ menu['id'] }}/web_icon_data line

I've tried to upgrade to original web_responsive, check developer console > network & I found nothing

**Comment by wangsamas** [comment] 2018-02-08 07:37
@lasley 

Hi, I want to confirm that those line cause Access Denied.

I install material / united backend theme from openworx which an extension from web_responsive.
After installation I get Access Denied from that module too. I found that it also have a similar line as web_responsive

<img t-attf-src="/web/image/ir.ui.menu/{{ menu['id'] }}/web_icon_data" t-att-alt="menu['name']" class="app-sidebar-menuitem" t-att-title="menu['name']"/>
                                
After I delete this line and re install the theme, the Access Denied don't appear.

I don't know what should I do with this. 
I love web_responsive, the basic odoo is very ugly in mobile phone.
Now I don't get any wierd warnings but I have to sacrifice the beautiful icons.
please help.

**Comment by pedrobaeza** [comment] 2018-02-08 07:40
But that's something only on your side. We are using the module since the beginning without any issue, so it should be any kind on custom access rule / custom module you have. If you replicate it the problem in our runbot, then we can confirm it, but for now, this is only a bad use of Odoo IMO.

**Comment by wangsamas** [comment] 2018-02-08 07:43
Hi pedrobaeza,
how can I replicate in your runbot & what is Odoo IMO?
Thx

**Comment by pedrobaeza** [comment] 2018-02-08 07:46
IMO: In My Opinion

And there's a button on the module README that put "Try me on runbot". Click there and use admin/admin, but right now, our runbot is down due to some server issues, but try later.

**Comment by wangsamas** [comment] 2018-02-08 07:49
Ok

**Comment by wangsamas** [comment] 2018-02-23 03:02
Hi all, I installed odoo in fresh local PC using steps from here https://github.com/Yenthe666/InstallScript
it was successful but I get this in my log.

2018-02-23 02:47:12,530 25001 INFO ? werkzeug: 192.168.1.108 - - [23/Feb/2018 02:47:12] "GET /base/static/description/icon.png HTTP/1.1" 20$
2018-02-23 02:47:12,532 25001 INFO ? werkzeug: 192.168.1.108 - - [23/Feb/2018 02:47:12] "GET /account_asset/static/description/icon.png HTT$
2018-02-23 02:47:12,535 25001 INFO ? werkzeug: 192.168.1.108 - - [23/Feb/2018 02:47:12] "GET /hr_payroll/static/description/icon.png HTTP/1$
2018-02-23 02:47:12,545 25001 INFO ? werkzeug: 192.168.1.108 - - [23/Feb/2018 02:47:12] "GET /account_check_printing/static/description/ico$
2018-02-23 02:47:12,545 25001 INFO ? werkzeug: 192.168.1.108 - - [23/Feb/2018 02:47:12] "GET /website_crm/static/description/icon.png HTTP/$
2018-02-23 02:47:12,549 25001 INFO ? werkzeug: 192.168.1.108 - - [23/Feb/2018 02:47:12] "GET /event/static/description/icon.png HTTP/1.1" 2$

they are not writen as 'warnings' but as '?', and the contents are the same as problem that I mention here... icon.png
so I think the problem is not from web_responsive or bitnami installation, but from odoo it self... right?

**Comment by wangsamas** [comment] 2018-10-18 05:37
Hi all,

I found that this ACL problem caused by this line in web.xml
<img t-attf-src="/web/image/ir.ui.menu/{{ menu['id'] }}/web_icon_data"

by default odoo doesn't give access Technical Feature Group to access ir.ui.menu.
to fix this add read access to Technical Feature Group to read ir.ui.menu

hopefully this help anyone who face the same problem
